# A default rule that gets us to actions outside of the CMS.
# Note that you can't have pages with a slug beginning with /admin
# on a site that uses this particular rule. You could use a 
# different prefix. Or you could provide rules for every
# module, or even for every action. This is just the simplest way.

default:
  url:   /admin/:module/:action/*

# A homepage rule is expected by a and various other plugins,
# so be sure to have one

homepage:
  url:  /
  param: { module: a, action: show, slug: / }

# Put any routing rules for other modules and actions HERE,
# before the catch-all rule that routes URLs to the
# CMS by default.

# Must be the last rule

a_page:
  url:   /:slug
  param: { module: a, action: show }
  requirements: { slug: .* }


