<?php

/**
 * BaseaMediaCategory
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $name
 * @property string $description
 * @property Doctrine_Collection $MediaItems
 * @property Doctrine_Collection $Pages
 * @property Doctrine_Collection $aMediaItemCategory
 * @property Doctrine_Collection $aMediaPageCategory
 * 
 * @method integer             getId()                 Returns the current record's "id" value
 * @method string              getName()               Returns the current record's "name" value
 * @method string              getDescription()        Returns the current record's "description" value
 * @method Doctrine_Collection getMediaItems()         Returns the current record's "MediaItems" collection
 * @method Doctrine_Collection getPages()              Returns the current record's "Pages" collection
 * @method Doctrine_Collection getAMediaItemCategory() Returns the current record's "aMediaItemCategory" collection
 * @method Doctrine_Collection getAMediaPageCategory() Returns the current record's "aMediaPageCategory" collection
 * @method aMediaCategory      setId()                 Sets the current record's "id" value
 * @method aMediaCategory      setName()               Sets the current record's "name" value
 * @method aMediaCategory      setDescription()        Sets the current record's "description" value
 * @method aMediaCategory      setMediaItems()         Sets the current record's "MediaItems" collection
 * @method aMediaCategory      setPages()              Sets the current record's "Pages" collection
 * @method aMediaCategory      setAMediaItemCategory() Sets the current record's "aMediaItemCategory" collection
 * @method aMediaCategory      setAMediaPageCategory() Sets the current record's "aMediaPageCategory" collection
 * 
 * @package    gri
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseaMediaCategory extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('a_media_category');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'unique' => true,
             'length' => 255,
             ));
        $this->hasColumn('description', 'string', null, array(
             'type' => 'string',
             ));

        $this->option('type', 'INNODB');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('aMediaItem as MediaItems', array(
             'refClass' => 'aMediaItemCategory',
             'local' => 'media_category_id',
             'foreign' => 'media_item_id'));

        $this->hasMany('aPage as Pages', array(
             'refClass' => 'aMediaPageCategory',
             'local' => 'media_category_id',
             'foreign' => 'page_id'));

        $this->hasMany('aMediaItemCategory', array(
             'local' => 'id',
             'foreign' => 'media_category_id'));

        $this->hasMany('aMediaPageCategory', array(
             'local' => 'id',
             'foreign' => 'media_category_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $sluggable0 = new Doctrine_Template_Sluggable();
        $this->actAs($timestampable0);
        $this->actAs($sluggable0);
    }
}